<a href="https://colab.research.google.com/github/citjimm/DMDS/blob/main/PS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import pandas_datareader as pdr
from pandas_datareader import wb
from pandas.io.formats.style import Styler
import matplotlib.pyplot as plt

In [4]:
#!wget -q -O edad.xlsx https://raw.githubusercontent.com/citjim/raw/main/edad.xlsx #aok no it doesnt work
!wget -q -O edad.xlsx https://github.com/citjimm/DMDS/raw/main/edad.xlsx
#https://github.com/citjimm/DMDS/raw/main/edad.xlsx
pd.read_excel('edad.xlsx') #aok misspelled here
#and read in the right chunk; or rename var to sth meaningful and drop rows that are junk
# see links on excel in class notebook

,"Table EDAd. Emergency department visits within the past 12 months among adults aged 18 and over, by selected characteristics: United States, selected years 1997–2019",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92
0,Excel version (with more data years and standa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[Data are based on household interviews of a s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Characteristic,One or more emergency department visits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1997,SE,1998,SE,1999,SE,2000,SE,2001,...,2015,SE,2016,SE,2017,SE,2018,SE,2019,SE
4,NaN,Percent of adults with emergency department vi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Within MSA,19.1,0.3,19,0.3,16.6,0.3,19.6,0.3,19.3,...,6.5,0.2,6.4,0.2,6.3,0.2,7.9,0.2,8.4,0.2
73,Outside MSA,21.5,0.6,22.3,0.6,19.5,0.7,22.5,0.6,21.3,...,9.6,0.7,9.4,0.7,8,0.6,10.6,0.7,8.8,0.6
74,… Category not applicable.\n* Estimates are co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,"NOTES: Respondents were asked, ""During the pas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,"SOURCE: National Center for Health Statistics,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

#aok: breaks again: no such file
!wget -q -O edad.csv https://drive.google.com/uc?id=1wEs1JH2J5r3JR4IIkoWqUsfYbcb_0S26/&export=download

#https://drive.google.com/file/d/1wEs1JH2J5r3JR4IIkoWqUsfYbcb_0S26/view?usp=drive_link
#pd.read_excel ('https://drive.google.com/uc?id=1fSLZfISAbn_jYF5f9I6t5Y3mx0WAiVMd/&export=download')

pd.read_csv ('edad.csv')

EmptyDataError: ignored

Census Data- HTML - Wikipedia

In [6]:
import html
#dt=
pd.read_html('https://en.wikipedia.org/wiki/2020_United_States_census',match='Change',flavor=None)[0].head(52)

dat= pd.read_html('https://en.wikipedia.org/wiki/2020_United_States_census',match='Change',flavor=None)[0].head(52)

dat

dat.columns

dat.describe()

dat.Change

dat

#state_changes = dat[['State','Change']]





#Was attempting to use to creat bar graph of change


#state_changes.plot(kind='bar', x='State', y='Change', figsize=(12, 8), legend=False)
#plt.xlabel('State')
#plt.ylabel('Population change')
#plt.title('Percent change in population by State (2020 Census)')
#plt.xticks(rotation=90)  # Rotate state labels for better readability
#plt.show()

,Rank,State,Population as of 2020 census[85],Population as of 2010 census[86],Change,Percent change
0,1,California,39538223,37253956,2284267,6.1%
1,2,Texas,29145505,25145561,3999944,15.9%
2,3,Florida,21538187,18801310,2736877,14.6%
3,4,New York,20201249,19378102,823147,4.3%
4,5,Pennsylvania,13002700,12702379,300321,2.4%
5,6,Illinois,12812508,12830632,"−18,124",−0.1%
6,7,Ohio,11799448,11536504,262944,2.3%
7,8,Georgia,10711908,9687653,1024255,10.6%
8,9,North Carolina,10439388,9535483,903905,9.5%
9,10,Michigan,10077331,9883640,193691,2.0%
10,11,New Jersey,9288994,8791894,497100,5.7%
11,12,Virginia,8631393,8001024,630369,7.9%
12,13,Washington,7705281,6724540,980741,14.6%
13,14,Arizona,7151502,6392017,759485,11.9%
14,15,Massachusetts,7029917,6547629,482288,7.4%
15,16,Tennessee,6910840,6346105,564735,8.9%
16,17,Indiana,6785528,6483802,301726,4.6%
17,18,Maryland,6177224,5773552,403672,7.0%
18,19,Missouri,6154913,5988927,165986,2.8%
19,20,Wisconsin,5893718,5686986,206732,3.6%
20,21,Colorado,5773714,5029196,744518,14.8%
21,22,Minnesota,5706494,5303925,402569,7.6%
22,23,South Carolina,5118425,4625364,493061,10.7%
23,24,Alabama,5024279,4779736,244543,5.1%
24,25,Louisiana,4657757,4533372,124385,2.7%
25,26,Kentucky,4505836,4339367,166469,3.8%
26,27,Oregon,4237256,3831074,406182,10.6%
27,28,Oklahoma,3959353,3751351,208002,5.5%
28,29,Connecticut,3605944,3574097,31847,0.9%
29,30,Utah,3271616,2763885,507731,18.4%
30,31,Iowa,3190369,3046355,144014,4.7%
31,32,Nevada,3104614,2700551,404063,15.0%
32,33,Arkansas,3011524,2915918,95606,3.3%
33,34,Mississippi,2961279,2967297,"−6,018",−0.2%
34,35,Kansas,2937880,2853118,84762,3.0%
35,36,New Mexico,2117522,2059179,58343,2.8%
36,37,Nebraska,1961504,1826341,135163,7.4%
37,38,Idaho,1839106,1567582,271524,17.3%
38,39,West Virginia,1793716,1852994,"−59,278",−3.2%
39,40,Hawaii,1455271,1360301,94970,7.0%
40,41,New Hampshire,1377529,1316470,61059,4.6%
41,42,Maine,1362359,1328361,33998,2.6%
42,43,Rhode Island,1097379,1052567,44812,4.3%
43,44,Montana,1084225,989415,94810,9.6%
44,45,Delaware,989948,897934,92014,10.3%
45,46,South Dakota,886667,814180,72487,8.9%
46,47,North Dakota,779094,672591,106503,15.8%
47,48,Alaska,733391,710231,23160,3.3%
48,—,District of Columbia,689545,601723,87822,14.6%
49,49,Vermont,643077,625741,17336,2.8%
50,50,Wyoming,576851,563626,13225,2.4%
51,NaN,United States,331449281,308745538,22703743,7.4%

Is there an issue with the data set itself?

aok: looks fine

In [7]:
!wget -q -O index.json https://drive.google.com/uc?id=16JKCFx676wzEvz8ZmNlgmWqpbD-qWDDT/&export=download
#aok no it doesnt load--if you put that url into webbrowser it doesnt exist
data= pd.read_json('index.json', lines=True)

# lines= true (from stack overflow) seems to have helped but then...

data.columns
#is there a problem in uploading the data???

Float64Index([], dtype='float64')

In [8]:
data

Empty DataFrame
Columns: []
Index: []